name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # First you need to install a chromium browser in your runner
        - name: Install Chromium
          run: sudo apt-get install chromium-browser
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 20
        - name: Install
          run: npm install
        - name: Test
          run: npx wdio .\wdio.conf.js
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs